import { Quicksand } from "next/font/google";

import Image from "next/image";
import { Metadata } from "next";

import "@/app/assets/globals.css";
import "@/app/assets/app.css";

import { Toolbarnav } from "@/app/components/Navbars/Toolbarnav";
import { Lato } from "next/font/google";
import { GlobalSearch } from "./components/Search/GlobalSearch";
import { MiddleNav } from "./components/Navbars/MiddleNav";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300","500" ,"400", "700"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}:{ children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} antialiased `}
      >
        <div className="">
          <Toolbarnav />
          <MiddleNav/>
        </div>
        {children}
      </body>
    </html>
  );
}
