import { Quicksand } from "next/font/google";

import Image from "next/image";
import { Metadata } from "next";

import "@/app/assets/globals.css";
import "@/app/assets/app.css";

import { Toolbarnav } from "@/app/components/Navbars/Toolbarnav";
import { Lato } from "next/font/google";
import { GlobalSearch } from "./components/Search/GlobalSearch";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300","500" ,"400", "700"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}:{ children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} antialiased `}
      >
        <div className="">
          <Toolbarnav />
          <div className="my-container h-[122.5px] flex items-center justify-between">

            
            <div className="hero-logo pr-[70px]">
              <Image src="/logo/logo.png" alt="Nest Mart & Grocery Logo" width={150} height={50} />
            </div>

            <div className="hero-search w-full  flex-1">
              <GlobalSearch />
            </div>

            <div className="">

            </div>

            <div className="">

            </div>

          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
